name: Create Bootable ISO and Publish Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate ISO
      run: |
        powershell .\generateiso.ps1

    - name: Get ADK Version
      id: get-version
      run: |
        echo "::set-output name=adk_version::$(cat .\adk_version.txt)"

    - name: Upload ISO to Release
      uses: softprops/action-gh-release@v1
      with:
        files: .\pe\WinPE_${{ steps.get-version.outputs.adk_version }}.iso
      env:
        TAG_NAME: "v${{ steps.get-version.outputs.adk_version }}"
        RELEASE_NAME: "WinPE ISO ${{ steps.get-version.outputs.adk_version }}"
